# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - bazel-*
    - vendor

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - typecheck
  disable:
    # Too noisy for now
    - godot
    - wsl
    - nlreturn
    - gofumpt

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives
  staticcheck:
    checks:
      - all

issues:
  exclude-rules:
    # Test files can have longer functions
    - path: _test\.go
      linters:
        - funlen
    # Generated files
    - path: \.pb\.go
      linters:
        - all
  max-issues-per-linter: 50
  max-same-issues: 10
