/**
 * Starlight Sidebar Orphan Page Validator
 *
 * This script validates that all MDX files in the docs content directory
 * are included in the sidebar navigation. It extracts all slugs from the
 * sidebar config and compares them against actual files.
 *
 * Usage: Run during build with `astro build` (integrated via astro.config.ts)
 */

import type { AstroIntegration } from 'astro';
import path from 'node:path';
import fs from 'node:fs';

/**
 * Recursively find all files matching a pattern in a directory
 */
function findFiles(dir: string, pattern: RegExp, files: string[] = []): string[] {
	const entries = fs.readdirSync(dir, { withFileTypes: true });

	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			findFiles(fullPath, pattern, files);
		} else if (pattern.test(entry.name)) {
			files.push(fullPath);
		}
	}

	return files;
}

/**
 * Converts a file path to a Starlight slug
 */
function filePathToSlug(filePath: string, docsDir: string): string {
	const relativePath = path.relative(docsDir, filePath);
	// Remove .mdx extension and convert to slug
	let slug = relativePath.replace(/\.mdx$/, '');
	// Handle index files (e.g., plugins/index.mdx -> plugins)
	slug = slug.replace(/\/index$/, '');
	// Handle root index
	if (slug === 'index') {
		return '';
	}
	return slug;
}

/**
 * Checks if a slug is covered by an autogenerate directory
 */
function isAutogenerated(slug: string, autogenerateDirs: Set<string>): boolean {
	for (const dir of autogenerateDirs) {
		if (slug.startsWith(dir + '/') || slug === dir) {
			return true;
		}
	}
	return false;
}

export interface ValidateSidebarOptions {
	/** If true, throws an error and fails the build when orphan pages are found */
	failOnOrphans?: boolean;
}

/**
 * Astro integration that validates sidebar navigation during build
 */
export function validateSidebar(options: ValidateSidebarOptions = {}): AstroIntegration {
	const { failOnOrphans = true } = options;

	return {
		name: 'validate-sidebar',
		hooks: {
			'astro:config:done': async () => {
				const docsDir = path.join(process.cwd(), 'src/content/docs');

				// Check if docs directory exists
				if (!fs.existsSync(docsDir)) {
					console.warn('[validate-sidebar] Docs directory not found:', docsDir);
					return;
				}

				// Find all MDX files
				const mdxFiles = findFiles(docsDir, /\.mdx$/);
				const relativeFiles = mdxFiles.map((f) => path.relative(docsDir, f));

				// Read the config file to extract sidebar configuration
				const configPath = path.join(process.cwd(), 'astro.config.ts');
				if (!fs.existsSync(configPath)) {
					console.warn('[validate-sidebar] Config file not found:', configPath);
					return;
				}

				const configContent = fs.readFileSync(configPath, 'utf-8');

				// Extract explicit slugs using regex
				const slugMatches = configContent.matchAll(/slug:\s*['"]([^'"]+)['"]/g);
				const explicitSlugs = new Set<string>();
				for (const match of slugMatches) {
					explicitSlugs.add(match[1]);
				}

				// Extract autogenerate directories
				const autogenMatches = configContent.matchAll(
					/autogenerate:\s*\{\s*directory:\s*['"]([^'"]+)['"]/g
				);
				const autogenerateDirs = new Set<string>();
				for (const match of autogenMatches) {
					autogenerateDirs.add(match[1]);
				}

				// Convert MDX files to slugs and check coverage
				const orphanPages: string[] = [];
				const skippedPages: string[] = [];

				for (const file of relativeFiles) {
					const slug = filePathToSlug(file, '');

					// Skip root index page (homepage)
					if (slug === '') {
						skippedPages.push(file);
						continue;
					}

					// Check if slug is in explicit list or covered by autogenerate
					const isExplicit = explicitSlugs.has(slug);
					const isAutoGen = isAutogenerated(slug, autogenerateDirs);

					if (!isExplicit && !isAutoGen) {
						orphanPages.push(file);
					}
				}

				// Report results
				console.log('\n[validate-sidebar] Navigation validation results:');
				console.log(`  Total MDX files: ${relativeFiles.length}`);
				console.log(`  In sidebar (explicit): ${explicitSlugs.size}`);
				console.log(
					`  Autogenerate directories: ${autogenerateDirs.size} (${[...autogenerateDirs].join(', ')})`
				);
				console.log(`  Skipped (homepage): ${skippedPages.length}`);

				if (orphanPages.length > 0) {
					console.error(
						`\n[validate-sidebar] ERROR: Found ${orphanPages.length} orphan page(s) not in navigation:`
					);
					for (const page of orphanPages) {
						const slug = filePathToSlug(page, '');
						console.error(`  - ${page} (slug: '${slug}')`);
					}
					console.error(
						'\nTo fix: Add these pages to the sidebar configuration in astro.config.ts'
					);
					console.error(
						'Either add them explicitly or use autogenerate for their directory.\n'
					);

					if (failOnOrphans) {
						throw new Error(
							`[validate-sidebar] Build failed: ${orphanPages.length} orphan page(s) found`
						);
					}
				} else {
					console.log('  Orphan pages: 0');
					console.log('[validate-sidebar] All pages are in the navigation!\n');
				}
			},
		},
	};
}

export default validateSidebar;
