// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: internal/starlark/builtins/proto/builtins.proto

package builtinspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Builtins struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*Type                `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Values        []*Value               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Builtins) Reset() {
	*x = Builtins{}
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Builtins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Builtins) ProtoMessage() {}

func (x *Builtins) ProtoReflect() protoreflect.Message {
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Builtins.ProtoReflect.Descriptor instead.
func (*Builtins) Descriptor() ([]byte, []int) {
	return file_internal_starlark_builtins_proto_builtins_proto_rawDescGZIP(), []int{0}
}

func (x *Builtins) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Builtins) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Doc           string                 `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_internal_starlark_builtins_proto_builtins_proto_rawDescGZIP(), []int{1}
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Type) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	Callable      *Callable              `protobuf:"bytes,4,opt,name=callable,proto3,oneof" json:"callable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_internal_starlark_builtins_proto_builtins_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Field) GetCallable() *Callable {
	if x != nil {
		return x.Callable
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	Callable      *Callable              `protobuf:"bytes,4,opt,name=callable,proto3,oneof" json:"callable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_internal_starlark_builtins_proto_builtins_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Value) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Value) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Value) GetCallable() *Callable {
	if x != nil {
		return x.Callable
	}
	return nil
}

type Callable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*Param               `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	ReturnType    string                 `protobuf:"bytes,2,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Callable) Reset() {
	*x = Callable{}
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Callable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Callable) ProtoMessage() {}

func (x *Callable) ProtoReflect() protoreflect.Message {
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Callable.ProtoReflect.Descriptor instead.
func (*Callable) Descriptor() ([]byte, []int) {
	return file_internal_starlark_builtins_proto_builtins_proto_rawDescGZIP(), []int{4}
}

func (x *Callable) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Callable) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

func (x *Callable) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	IsMandatory   bool                   `protobuf:"varint,5,opt,name=is_mandatory,json=isMandatory,proto3" json:"is_mandatory,omitempty"`
	IsStarArg     bool                   `protobuf:"varint,6,opt,name=is_star_arg,json=isStarArg,proto3" json:"is_star_arg,omitempty"`
	IsStarStarArg bool                   `protobuf:"varint,7,opt,name=is_star_star_arg,json=isStarStarArg,proto3" json:"is_star_star_arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_internal_starlark_builtins_proto_builtins_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_internal_starlark_builtins_proto_builtins_proto_rawDescGZIP(), []int{5}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Param) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Param) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *Param) GetIsMandatory() bool {
	if x != nil {
		return x.IsMandatory
	}
	return false
}

func (x *Param) GetIsStarArg() bool {
	if x != nil {
		return x.IsStarArg
	}
	return false
}

func (x *Param) GetIsStarStarArg() bool {
	if x != nil {
		return x.IsStarStarArg
	}
	return false
}

var File_internal_starlark_builtins_proto_builtins_proto protoreflect.FileDescriptor

const file_internal_starlark_builtins_proto_builtins_proto_rawDesc = "" +
	"\n" +
	"/internal/starlark/builtins/proto/builtins.proto\x12\fsky.builtins\"a\n" +
	"\bBuiltins\x12(\n" +
	"\x05types\x18\x01 \x03(\v2\x12.sky.builtins.TypeR\x05types\x12+\n" +
	"\x06values\x18\x02 \x03(\v2\x13.sky.builtins.ValueR\x06values\"Y\n" +
	"\x04Type\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03doc\x18\x02 \x01(\tR\x03doc\x12+\n" +
	"\x06fields\x18\x03 \x03(\v2\x13.sky.builtins.FieldR\x06fields\"\x87\x01\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x127\n" +
	"\bcallable\x18\x04 \x01(\v2\x16.sky.builtins.CallableH\x00R\bcallable\x88\x01\x01B\v\n" +
	"\t_callable\"\x87\x01\n" +
	"\x05Value\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x127\n" +
	"\bcallable\x18\x04 \x01(\v2\x16.sky.builtins.CallableH\x00R\bcallable\x88\x01\x01B\v\n" +
	"\t_callable\"j\n" +
	"\bCallable\x12+\n" +
	"\x06params\x18\x01 \x03(\v2\x13.sky.builtins.ParamR\x06params\x12\x1f\n" +
	"\vreturn_type\x18\x02 \x01(\tR\n" +
	"returnType\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\"\xd2\x01\n" +
	"\x05Param\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12!\n" +
	"\fis_mandatory\x18\x05 \x01(\bR\visMandatory\x12\x1e\n" +
	"\vis_star_arg\x18\x06 \x01(\bR\tisStarArg\x12'\n" +
	"\x10is_star_star_arg\x18\a \x01(\bR\risStarStarArgBNZLgithub.com/albertocavalcante/sky/internal/starlark/builtins/proto;builtinspbb\x06proto3"

var (
	file_internal_starlark_builtins_proto_builtins_proto_rawDescOnce sync.Once
	file_internal_starlark_builtins_proto_builtins_proto_rawDescData []byte
)

func file_internal_starlark_builtins_proto_builtins_proto_rawDescGZIP() []byte {
	file_internal_starlark_builtins_proto_builtins_proto_rawDescOnce.Do(func() {
		file_internal_starlark_builtins_proto_builtins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_starlark_builtins_proto_builtins_proto_rawDesc), len(file_internal_starlark_builtins_proto_builtins_proto_rawDesc)))
	})
	return file_internal_starlark_builtins_proto_builtins_proto_rawDescData
}

var file_internal_starlark_builtins_proto_builtins_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_starlark_builtins_proto_builtins_proto_goTypes = []any{
	(*Builtins)(nil), // 0: sky.builtins.Builtins
	(*Type)(nil),     // 1: sky.builtins.Type
	(*Field)(nil),    // 2: sky.builtins.Field
	(*Value)(nil),    // 3: sky.builtins.Value
	(*Callable)(nil), // 4: sky.builtins.Callable
	(*Param)(nil),    // 5: sky.builtins.Param
}
var file_internal_starlark_builtins_proto_builtins_proto_depIdxs = []int32{
	1, // 0: sky.builtins.Builtins.types:type_name -> sky.builtins.Type
	3, // 1: sky.builtins.Builtins.values:type_name -> sky.builtins.Value
	2, // 2: sky.builtins.Type.fields:type_name -> sky.builtins.Field
	4, // 3: sky.builtins.Field.callable:type_name -> sky.builtins.Callable
	4, // 4: sky.builtins.Value.callable:type_name -> sky.builtins.Callable
	5, // 5: sky.builtins.Callable.params:type_name -> sky.builtins.Param
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_starlark_builtins_proto_builtins_proto_init() }
func file_internal_starlark_builtins_proto_builtins_proto_init() {
	if File_internal_starlark_builtins_proto_builtins_proto != nil {
		return
	}
	file_internal_starlark_builtins_proto_builtins_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_starlark_builtins_proto_builtins_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_starlark_builtins_proto_builtins_proto_rawDesc), len(file_internal_starlark_builtins_proto_builtins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_starlark_builtins_proto_builtins_proto_goTypes,
		DependencyIndexes: file_internal_starlark_builtins_proto_builtins_proto_depIdxs,
		MessageInfos:      file_internal_starlark_builtins_proto_builtins_proto_msgTypes,
	}.Build()
	File_internal_starlark_builtins_proto_builtins_proto = out.File
	file_internal_starlark_builtins_proto_builtins_proto_goTypes = nil
	file_internal_starlark_builtins_proto_builtins_proto_depIdxs = nil
}
