name: 'Sky Test'
description: 'Run Starlark tests with skytest - cross-platform (Linux, macOS, Windows)'
author: 'albertocavalcante'

inputs:
  path:
    description: 'Path to test files'
    required: false
    default: '.'
  recursive:
    description: 'Search directories recursively'
    required: false
    default: 'true'
  coverage:
    description: 'Enable coverage collection'
    required: false
    default: 'false'
  coverage-threshold:
    description: 'Minimum coverage percentage (0 to disable)'
    required: false
    default: '0'
  annotations:
    description: 'Enable GitHub PR annotations'
    required: false
    default: 'true'
  summary:
    description: 'Write to job summary'
    required: false
    default: 'true'
  version:
    description: 'Sky version to install (e.g., latest, v0.1.0)'
    required: false
    default: 'latest'
  fail-fast:
    description: 'Stop on first test failure'
    required: false
    default: 'false'
  timeout:
    description: 'Timeout per test (Go duration format, e.g., 30s, 1m)'
    required: false
    default: '30s'

outputs:
  passed:
    description: 'Number of passed tests'
    value: ${{ steps.test.outputs.passed }}
  failed:
    description: 'Number of failed tests'
    value: ${{ steps.test.outputs.failed }}
  coverage:
    description: 'Coverage percentage'
    value: ${{ steps.test.outputs.coverage }}

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install sky tools
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          go install github.com/albertocavalcante/sky/cmd/skytest@latest
          go install github.com/albertocavalcante/sky/cmd/sky-ci@latest
        else
          go install github.com/albertocavalcante/sky/cmd/skytest@${{ inputs.version }}
          go install github.com/albertocavalcante/sky/cmd/sky-ci@${{ inputs.version }}
        fi

    # Pipeline pattern: skytest outputs JSON, sky-ci transforms to GitHub format
    # This is cross-platform - bash is available on all GitHub runners
    - name: Run tests
      id: test
      shell: bash
      run: |
        FLAGS=""
        if [ "${{ inputs.recursive }}" = "true" ]; then
          FLAGS="$FLAGS -r"
        fi
        if [ "${{ inputs.fail-fast }}" = "true" ]; then
          FLAGS="$FLAGS -x"
        fi
        if [ "${{ inputs.timeout }}" != "" ]; then
          FLAGS="$FLAGS -timeout=${{ inputs.timeout }}"
        fi

        # Run tests and pipe to CI reporter
        # shellcheck disable=SC2086
        skytest -json $FLAGS "${{ inputs.path }}" | sky-ci \
          --annotations=${{ inputs.annotations }} \
          --summary=${{ inputs.summary }} \
          --coverage-threshold=${{ inputs.coverage-threshold }}

branding:
  icon: 'check-circle'
  color: 'blue'
